### ISSUE TITLE
Änderungsverlust bei Validierungsfehler

### ISSUE THREAD

**Issue by maechler** [swissbib/libadmin#12]
Wenn man eine Institution bearbeitet und ein Validierungsfehler auf der Server-Seite auftritt, dann gehen Änderungen, die im Tab "Gruppen & Views" gemacht wurden, verloren. Dasselbe Problem besteht wenn man eine neue Institution erstellt.
Schlägt die Validierung nur client-seitig fehl passiert das nicht. (z.B. wenn Bib-Code leer ist)

Nachvollziehen kann man das so:
1) Unter "Institutionen" eine Institution zum Bearbeiten auswählen, oder eine neue Institution erstellen
2) Änderungen im Tab Gruppen & Views machen
3) Eine ungültige E-Mail Adresse im Tab Adresse angeben (z.B. ohne @ )
4) Institution speichern
5) Es gibt einen Validierungsfehler bei E-Mail und die Änderungen, die unter Gruppen & Views gemacht wurden sind verschwunden.

**Comment by guenterh** [comment]
wenn wir ihn nicht fixen dann schliessen wir den issue
