### ISSUE TITLE
Emailadresse @ehb.swiss lässt sich nicht speichern 

### ISSUE THREAD

**Issue by mschwendener** [swissbib/libadmin#13]
B418 hat als neue Emailadresse bibliothek@ehb.swiss - lässt sich nicht abspeichern.
    'ehb.swiss' is not a valid hostname for the email address
    The input appears to be a DNS hostname but cannot match TLD against known list
    The input appears to be a local network name but local network names are not allowed

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [13](https://trello.com/c/JsscmHeq/51-13)
