### ISSUE TITLE
Sortierung der Bibliotheken in der Trefferliste und in der Vollanzeige fehlt

### ISSUE THREAD

**Issue by mschwendener** [swissbib/libadmin#14]
Februar 2016 gemeldet: seit die Bibliotheken nicht mehr in libadmin sortiert werden, ist die Reihenfolge in /libraries zwar korrekt, in der Trefferliste und der Vollanzeige im Katalog aber nicht sortiert.

**Comment by edelm** [comment]
Sollen die Bibliotheken alphabetisch nach Display-Namen oder nach Code sortiert werden? Falls alphabetisch nach Display-Namen, müsste man die Sortierung wegen der unterschiedlichen Sprachen in VuFind implementieren. 

Im Moment wird der Displayname erst im letzten Moment, wenn die einzelnen Einträge im GUI dargestellt werden, geholt. Siehe https://github.com/swissbib/vufind/blob/master/themes/sbvfrd/templates/RecordTab/holdingsils.phtml#L55

**Comment by mschwendener** [comment]
Nach Display-Namen. 

Ist allerdings in den allermeisten Fällen in allen Sprachen identisch.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [14](https://trello.com/c/idiLdX0Y/52-14)

**Comment by mschwendener** [comment]
Bsp. [](https://www.swissbib.ch/Record/490993028)

**Comment by mschwendener** [comment]
![swissbib](https://user-images.githubusercontent.com/4497705/63327424-762bba80-c32e-11e9-87a9-35a7a5dab972.PNG)

**Comment by edelm** [comment]
Sortierung vom libadmin export (de.ini etc) ist pro libadmin-Gruppe alphabetisch (was auch in der Anzeige in VF erwünscht wäre).

**Comment by edelm** [comment]
Ich habe die Bibliotheken nun nach sprachabhängigem Anzeigenamen sortiert an folgenden Stellen:
- "mehr..." bei den Facetten (alphabetische Sortierung)
- Dropdownbox auf der Trefferliste
- Vollanzeige

**Comment by liowalter** [comment]
@mschwendener : could you have a look at https://test.swissbib.ch ? For example https://test.swissbib.ch/Record/260837474. 

@edelm : what do mean by "mehr..." bei den Facetten ? Hier sehe ich gar nichts : https://test.baselbern.swissbib.ch/Search/Results?lookfor=algebra&type=AllFields

**Comment by edelm** [comment]
> @edelm : what do mean by "mehr..." bei den Facetten ?

In swissbib classic you can sort the library network facet alphabetically (click on 'more' below the facet):
https://www.swissbib.ch/Search/Results?lookfor=ja&type=AllFields&limit=20

**Comment by liowalter** [comment]
Ok good ! Now I understood.

Could you do the same with the library facet on orange ? I.e. add an alphabetical sort option ? Or are there too many libraries ?

Lionel

**Comment by edelm** [comment]
We could get rid of 'themes/sbvfrd/templates/search/facet-list.phtml' to enable alphabetic sort in BB again. I don't think the amoutn of libraries should slow it down noticeably.

**Comment by mschwendener** [comment]
> @mschwendener : could you have a look at https://test.swissbib.ch ? For example https://test.swissbib.ch/Record/260837474.

@liowalter Looks good, thank you. 
Also https://test.swissbib.ch/Search/Results?lookfor=duden+rechtschreibung&type=AllFields&limit=20 -> scroll down until the third one from the bottom (with 33 libraries).

---

Facets
https://test.swissbib.ch/Search/Results?lookfor=duden+rechtschreibung&type=AllFields 
Mostly looking good (after clicking on the + next to a city name). 
Exceptions
Basel Stadt -> E75 instead of name
Bern -> B424 instead of name; RUAG before B...
Wallis -> École after Z...
Zürich -> E59 insted of name
