### ISSUE TITLE
gesucht: Lösung zur maschinellen Integration von Daten

### ISSUE THREAD

**Issue by guenterh** [swissbib/libadmin#15]
Problem (ein Beispiel): @witzigs  hat sehr aufwendig die Mailadressen von mehr als 300 Bibliotheken zusammengetragen (crowdfunding swissbib). Diese Arbeit sollte nicht verloren gehen und die Mailadressen Teil der Daten von Libadmin werden.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [15](https://trello.com/c/uZPp434j/53-15)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [15](https://trello.com/c/uZPp434j/53-15)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [15](https://trello.com/c/uZPp434j/53-15)
