### ISSUE TITLE
Kosmetik auf /Libraries

### ISSUE THREAD

**Issue by mschwendener** [swissbib/libadmin#19]
Wäre es möglich, auf https://www.swissbib.ch/Libraries in der linken Spalte deutlicher darzustellen, wenn ein neuer Verbund anfängt? Z.B. indem der Name des Verbundes weiss auf dunkelgrün geschrieben ist, so wie in der rechten Spalte? 

Und etwas mehr Abstand vor dem Titel des neuen Verbundes?

**Comment by liowalter** [comment]
fixed with swissbib 5.3.0.
