### ISSUE TITLE
Sortierung in View nach Bearbeitung einer Institution

### ISSUE THREAD

**Issue by oschihin** [swissbib/libadmin#4]
Problem
----------
Die Sortierung einer Instititution in der View richtet sich nach dem Wert im Feld 'position' im entsprechenden json-File:
```json
{
id": 2392,
"bib_code": "A100",
"sys_code": "A100",
"position": "638",
"favorite": true,
...
}
```
Bearbeitet man eine Institution, wird sie in libadmin in der Ansicht "View -> Institutionen sortieren" bei allen Views an erster Stelle angezeigt. Im json-File erhält sie einen Wert position=0
```json
{
id": 2392,
"bib_code": "A100",
"sys_code": "A100",
"position": "0",
"favorite": true,
...
}
```
Weswegen nach Bearbeitungen in libadmin in jeder View die Institutionen neu sortiert werden müssen. (siehe letzten Kommentar von @mschwendener hier: swissbib/sbvf2#107)

Lösung
---------
1. Analyse: Wieso wird der Sortierwert auf 0 gesetzt, wie entsteht er und wie bleibt er erhalten?
2. Lösung: Der Sortierwert bleibt beim speichern einer Institution erhalten und wird korrekt ausgegeben über die Schnittstelle

**Comment by guenterh** [comment]
Meine aktuelle Analyse ergibt folgendes:
Durch den Wechsel von ZF 2.2.5 zu 2.2.6 hat es unter anderem in der Implementierung der add - Element Methode eines Fieldset Elements eine Änderung gegeben.
https://github.com/swissbib/libadmin/blob/feature/nextMaster_mergedWithDevelop_moreCode/module/Libadmin/src/Libadmin/Form/InstitutionFieldset.php#L227

In 2.2.5 gab es noch folgendes Stückchen code zum Vorbereiten eines Fieldset Elements

        if ($elementOrFieldset instanceof FieldsetInterface) {
            if ($elementOrFieldset instanceof FieldsetPrepareAwareInterface) {
                $elementOrFieldset->prepareFieldset();
            }

prepareFieldset ist in 2.2.6 weggefallen.

Vor allem bei eingebundenen Collections führt das dazu, dass die Collectionobjekte nicht mehr gebunden werden. Das kann man möglicherweise selber steuern, indem man die prepare Methode selber aufruft (was ich an dieser Stelle im Controller mache: https://github.com/swissbib/libadmin/blob/feature/nextMaster_mergedWithDevelop_moreCode/module/Libadmin/src/Libadmin/Controller/InstitutionController.php#L95

Der dahinter stehende Mechanismus verlangt die Implemenierung von bestimmten Schnittstellen (Traversable und ArrayAccess) was ich mal testweise für das ModelItem InstitutionRelation gemacht habe. 
Ein Aufruf ist nun ohne Fehler möglich, die Werte werden aber immer noch nicht gebunden ....

Weitere Hinweise zu Anpassungen durch den ZF Releaseupdate:
http://framework.zend.com/changelog/2.2.6/
https://github.com/zendframework/zf2/pull/5502

@maechler: any ideas?

@oschihin z.K.


Der Branch, auf dem die aktuellen Anpassungen implementiert sind:

**Comment by mschwendener** [comment]
Aktueller Stand testl
- Änderung an Bibliotheksname: die geänderte Bibliothek steht bei den Views nicht mehr zuoberst - aber die Sortierung wird nicht aktualisiert!! D.h. im Gegensatz zur Produktion merke ich jetzt nicht mehr, dass die Sortierung falsch ist. Bsp: Alexandria umbenannt zu TEST Alexandria - sortiert weiterhin unter Al.. 

![test](https://cloud.githubusercontent.com/assets/4497705/11497467/8db04c50-9819-11e5-8e08-7426d8972ef8.JPG)
ibadmin:

**Comment by oschihin** [comment]
@maechler @mschwendener @guenterh 
Im Issue (ganz weit oben ;-) steht als Lösung: "Der Sortierwert bleibt beim speichern einer Institution erhalten und wird korrekt ausgegeben über die Schnittstelle." Das neue Verhalten entspricht dem offenbar. Was heisst das:
* Ein Bearbeiten einer Institution ändert den Sortierwert nicht (z.B. ändern der Telefonnummer, Notiz hinzu). Super!
* Ein Ändern des Bibliotheksnamens (also des Sortierwerts) hat denselben Effekt, der Sortierwert bleibt erhalten. Schade.

Nun könnte man natürlich (theoretisch, die Frage der Machbarkeit überlasse ich @maechler) nach dem Ändern dieses Felds eine Sortieraktion in allen Views auslösen. Ev. ist das etwas dick aufgetragen. Bibliotheksnamen ändern nicht alle Tage, ich könnte auch mit der Anleitung leben: Ändert man den Namen, muss man manuell neu sortieren.

**Comment by mschwendener** [comment]
Längerfristig gedacht müsste es eine Lösung sein, die auch dann noch funktioniert, falls wir eine Weboberfläche haben, auf der die Bibliotheken ihre eigenen Angaben ändern können. Den Anzeigenamen in swissbib sollen sie aber sowieso nicht ändern können, d.h. Feld "Display Namen" würden wir weiterhin selbst verwalten und können Sortierung von Hand auslösen.

**Comment by guenterh** [comment]
@maechler  @mschwendener @oschihin 

Hallo zusammen,
Manu: wenn ich Deine Comments richtig interpretiere, entspricht die getestete Funktionalität der der produktiven Instanz. Konkret: Es gehen keine Informationen bei Mutationen mehr verloren (wie in diesem issue zu Anfang beschrieben) und Du kannst Informationen korrekt  hinzufügen oder bewusst löschen.

an alle: ich bin dagegen, jetzt die Machbarkeit von wünschbaren Sortierfunktionen zu prüfen. Mein Standpunkt: 
1) wir sollten uns darauf konzentrieren, jetzt wieder eine stabile Applikation auf Basis der ursprünglich von snowflake implementierten Funktionalität zu erhalten, die als Basis für weitere  Ergänzungen dienen kann
2) wenn 1) erreicht, können wir die Erweiterung von https://github.com/swissbib/libadmin/issues/7 angehen. Danach werde 'ich' vorerst keine Arbeit mehr für Libadmin investieren. Auch Markus sollte das nicht machen (müssen)

Morgen werde ich noch die API von libadmintest testen. Wenn das ok ist, bereite ich ein brauchbares Deployment vor, räume die bestehenden Branches auf (einschliesslich Merge einer Formeta-API für Metafacture) und verteile ein Release als produktive Version

Günter

**Comment by maechler** [comment]
Hallo Zusammen,

Zur Sortierung:
Die Sortierung ist nicht rein alphabetisch. Es hat zwar einen Knopf für die alphabetische Sortierung, man kann die Institutionen aber auch beliebig von Hand sortieren. Somit kann man bei der Änderung des Namens die Institution auch nicht einfach neu alphabetisch einsortieren.
Wäre eine rein alphabetische Sortierung gewünscht, könnte man das wohl ohne allzu viel Aufwand aus der View entfernen und die Institutionen einfach vor der Rückgabe an VuFind über die API sortieren.

**Comment by mschwendener** [comment]
> Wäre eine rein alphabetische Sortierung gewünscht 
Ja, wäre sie (also jeweils innerhalb einer Gruppe, s. https://www.swissbib.ch/Libraries) - inkl. korrekter Sortierung von Sonderzeichen.  

> Es gehen keine Informationen bei Mutationen mehr verloren
Situation auf dem Screenshot von osc (https://github.com/swissbib/libadmin/issues/4#issuecomment-38274983) ist jedenfalls geflickt.

**Comment by guenterh** [comment]
API auf testvf gegen admin.swissbib.ch/libadmintest gestetet
TestCase
* Ändere link zu Bibliotheksinformationen im deutecsh Kontext auf www.woz.ch
* wurde nach Import korrekt übernommen

**Comment by guenterh** [comment]
Mapportal API gegen libadmintest ok
getestet auf sb-vf4

**Comment by guenterh** [comment]
* Deployment von https://github.com/swissbib/libadmin/releases/tag/R1.0 für libadmin und libadmintest
* Anpassung der scripte für libadmin in deployrep
* @witzigs : Bitte Ergebnis der API Nutzung in der kommenden Nacht für Basel / Bern überprüfen
Danke! Günter
