### ISSUE TITLE
Feld "Facebook" zu kurz

### ISSUE THREAD

**Issue by oschihin** [swissbib/libadmin#5]
## Problem
Das Feld "Facebook" ist zu kurz: Ich kann https://www.facebook.com/universitaetsbibliothek.basel eingeben, aber der Link wird beim Speichern abgeschnitten bei https://www.facebook.com/universitaetsbibliot

**Comment by guenterh** [comment]
@oschihin 

gefixt, Feld war mit varchar(45) zu klein.
Auf varchar(100) vergrössert und die Facebookadresse von A100 eingetragen

Auf libadmintest nachgezogen.

select facebook from institution where bib_code = 'A100';
+--------------------------------------------------------+
| facebook                                               |
+--------------------------------------------------------+
| https://www.facebook.com/universitaetsbibliothek.basel |
+--------------------------------------------------------+
1 row in set (0.00 sec)
