### ISSUE TITLE
URLs je Sprache

### ISSUE THREAD

**Issue by oschihin** [swissbib/libadmin#6]
Nur als Info: Wäre inhaltlich sinnvoller, die Bibinfo-Links nur in einem Feld zu haben (= identisch in allen Sprachen) und den Website/Homepage-Link in 4 Feldern, d.h. mit Anpassungsmöglichkeiten pro Sprache. Kann aber so bleiben.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [123](https://trello.com/c/SFy9s5GZ/49-123)

**Comment by mschwendener** [comment]
Ist erledigt, aber ich kann selber nicht schliessen.
