### ISSUE TITLE
Eweiterung um zusätzliche Felder

### ISSUE THREAD

**Issue by oschihin** [swissbib/libadmin#7]
## Thema

Um die Verlinkung mit weiteren Datenquellen zu ermöglichen und ev. weitere Funktionalitäten anbieten zu können, sollte libadmin um folgende Felder erweitert werden:
- [ ] Twitter 
- [ ] OCLC-Symbol
- [ ] WorldCat Registry ID;  Beispiele: 
  - http://worldcat.org/webservices/registry/enhancedContent/Institutions/112516
  - http://worldcat.org/registry/Identifiers/112516

**Comment by mschwendener** [comment]
Wenn ich aus meiner Sicht ergänzen darf, im Hinblick auf eine eventuelle Webschnittstelle für die Bibliotheken (Hackathon Juli 2016?): zusätzlich praktisch fände ich
- neues Feld Adresszusatz 
(für Postfach, Etage etc: ich erfasse diese im Moment nicht, damit eine Karten-Anwendung bessere Chancen hat, die Adresse richtig zu interpretieren)
- neues Feld öffentliche Notiz 
(Bsp.: einige der Bibliotheken sind nicht öffentlich zugänglich oder haben längere Umzugsperioden etc. Das momentan existierende Notizfeld benutze ich für interne Bearbeitungs-Notizen).

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [213](https://trello.com/c/MeYBfC1i/50-213)

**Comment by mschwendener** [comment]
Twitter, WorldCat, Adresszusatz und öffentliche Notiz sind erledigt.

**Comment by liowalter** [comment]
OCLC symbol has name Worldcat symbol. We don't need worldcat registry id for now.
